\i 'Stage 1 - Tables.sql'
\i 'Stage 2 - Default Values.sql'
\i 'Stage 3 - Views.sql'
\i 'Stage 4 - Admin Functions.sql'
\i 'Stage 5 - User Functions.sql'
\i 'Stage 6 - Security.sql'
\i 'Stage 7 - Manager Functions.sql'
\i 'Stage 8 - Employee Functions.sql'